version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: docker-resources/Dockerfile_Local
    ports:
      - "5000:5000"
    links:
      - "db:db"
    env_file:
      - docker-resources/env/api.env
    volumes:
      - "./:/code"
    command: ["python", "-m", "flask", "run"]
  app:
    build:
      context: .
      dockerfile: docker-resources/Dockerfile_Local
    ports:
      - "5001:5000"
    links:
      - "db:db"
    env_file:
      - docker-resources/env/app.env
    volumes:
      - "./:/code"
    command: [ "python", "-m", "flask", "run" ]
  db:
    image: postgres
    env_file:
      - docker-resources/env/db.env
    ports:
      - "5432:5432"
    volumes:
      - ~/Projects/db/yellow-pages-dev:/var/lib/postgresql/data